// Dozwolone przejścia stanów - backend używa ich do blokowania pominięcia
// obowiązkowych etapów aukcji, spotkania, wpłaty i przekazania.

export type ListingStatus =
  | "SZKIC"
  | "OCZEKUJE_NA_MODERACJE"
  | "WYMAGA_POPRAWY"
  | "ZATWIERDZONA"
  | "AKTYWNA"
  | "ZAKONCZONA"
  | "ANULOWANA_PRZED_LICYTACJA"
  | "ANULOWANA_PRZEZ_ADMINISTRATORA";

export const LISTING_TRANSITIONS: Record<ListingStatus, ListingStatus[]> = {
  SZKIC: ["OCZEKUJE_NA_MODERACJE"],
  OCZEKUJE_NA_MODERACJE: [
    "ZATWIERDZONA",
    "WYMAGA_POPRAWY",
    "ANULOWANA_PRZEZ_ADMINISTRATORA",
  ],
  WYMAGA_POPRAWY: ["OCZEKUJE_NA_MODERACJE", "ANULOWANA_PRZED_LICYTACJA"],
  ZATWIERDZONA: ["AKTYWNA", "ANULOWANA_PRZEZ_ADMINISTRATORA"],
  AKTYWNA: ["ZAKONCZONA", "ANULOWANA_PRZEZ_ADMINISTRATORA"],
  ZAKONCZONA: [],
  ANULOWANA_PRZED_LICYTACJA: [],
  ANULOWANA_PRZEZ_ADMINISTRATORA: [],
};

export function canTransitionListing(from: ListingStatus, to: ListingStatus): boolean {
  return LISTING_TRANSITIONS[from]?.includes(to) ?? false;
}

export type TransactionStatus =
  | "OCZEKUJE_NA_POTWIERDZENIE_ZWYCIEZCY"
  | "UMAWIANIE_SPOTKANIA"
  | "SPOTKANIE_ZAPLANOWANE"
  | "OBIE_STRONY_NA_MIEJSCU"
  | "OGLEDZINY"
  | "PRZEDMIOT_ZAAKCEPTOWANY"
  | "OCZEKIWANIE_NA_OTWARCIE_TERMINALU"
  | "TERMINAL_OTWARTY"
  | "OCZEKIWANIE_NA_BLIK"
  | "WPLATA_ZATWIERDZONA_PRZEZ_KUPUJACEGO"
  | "WPLATA_POTWIERDZONA_PRZEZ_SPRZEDAJACEGO"
  | "WPLATA_POTWIERDZONA_OBUSTRONNIE"
  | "WPLATA_NIEUDANA"
  | "WPLATA_WYMAGA_WYJASNIENIA"
  | "OCZEKUJE_NA_PLATNOSC"
  | "PLATNOSC_ODLOZONA"
  | "OCZEKUJE_NA_WERYFIKACJE"
  | "PONOWNY_ODBIOR_WYMAGANY"
  | "PROBLEM_Z_PLATNOSCIA"
  | "PRZEDMIOT_PRZEKAZANY"
  | "ZAKONCZONA_POMYSLNIE"
  | "ZWYCIEZCA_NIE_POTWIERDZIL"
  | "NIEOBECNOSC_KUPUJACEGO"
  | "NIEOBECNOSC_WYSTAWIAJACEGO"
  | "PRZEDMIOT_NIEZGODNY_Z_OPISEM"
  | "WPLATA_NIEPOTWIERDZONA"
  | "ODMOWA_PRZEKAZANIA"
  | "SPOR"
  | "ANULOWANA";

export const TRANSACTION_TRANSITIONS: Record<TransactionStatus, TransactionStatus[]> = {
  OCZEKUJE_NA_POTWIERDZENIE_ZWYCIEZCY: [
    "UMAWIANIE_SPOTKANIA",
    "ZWYCIEZCA_NIE_POTWIERDZIL",
  ],
  UMAWIANIE_SPOTKANIA: ["SPOTKANIE_ZAPLANOWANE"],
  SPOTKANIE_ZAPLANOWANE: [
    "OBIE_STRONY_NA_MIEJSCU",
    "NIEOBECNOSC_KUPUJACEGO",
    "NIEOBECNOSC_WYSTAWIAJACEGO",
  ],
  OBIE_STRONY_NA_MIEJSCU: ["OGLEDZINY"],
  OGLEDZINY: ["PRZEDMIOT_ZAAKCEPTOWANY", "PRZEDMIOT_NIEZGODNY_Z_OPISEM"],
  PRZEDMIOT_ZAAKCEPTOWANY: [
    "OCZEKIWANIE_NA_OTWARCIE_TERMINALU",
    "OCZEKUJE_NA_PLATNOSC",
    "OCZEKUJE_NA_WERYFIKACJE",
    "PLATNOSC_ODLOZONA",
  ],
  OCZEKIWANIE_NA_OTWARCIE_TERMINALU: [
    "TERMINAL_OTWARTY",
    "WPLATA_NIEUDANA",
    "WPLATA_WYMAGA_WYJASNIENIA",
    "PLATNOSC_ODLOZONA",
  ],
  TERMINAL_OTWARTY: [
    "OCZEKIWANIE_NA_BLIK",
    "WPLATA_NIEUDANA",
    "WPLATA_WYMAGA_WYJASNIENIA",
  ],
  OCZEKIWANIE_NA_BLIK: [
    "WPLATA_ZATWIERDZONA_PRZEZ_KUPUJACEGO",
    "WPLATA_POTWIERDZONA_PRZEZ_SPRZEDAJACEGO",
    "WPLATA_POTWIERDZONA_OBUSTRONNIE",
    "WPLATA_NIEUDANA",
    "WPLATA_WYMAGA_WYJASNIENIA",
  ],
  WPLATA_ZATWIERDZONA_PRZEZ_KUPUJACEGO: [
    "WPLATA_POTWIERDZONA_OBUSTRONNIE",
    "WPLATA_WYMAGA_WYJASNIENIA",
  ],
  WPLATA_POTWIERDZONA_PRZEZ_SPRZEDAJACEGO: [
    "WPLATA_POTWIERDZONA_OBUSTRONNIE",
    "WPLATA_WYMAGA_WYJASNIENIA",
  ],
  OCZEKUJE_NA_PLATNOSC: [
    "WPLATA_POTWIERDZONA_OBUSTRONNIE",
    "PLATNOSC_ODLOZONA",
    "PROBLEM_Z_PLATNOSCIA",
  ],
  OCZEKUJE_NA_WERYFIKACJE: [
    "WPLATA_POTWIERDZONA_OBUSTRONNIE",
    "PLATNOSC_ODLOZONA",
    "PROBLEM_Z_PLATNOSCIA",
  ],
  PLATNOSC_ODLOZONA: [
    "OCZEKUJE_NA_PLATNOSC",
    "OCZEKUJE_NA_WERYFIKACJE",
    "PONOWNY_ODBIOR_WYMAGANY",
    "PROBLEM_Z_PLATNOSCIA",
  ],
  PONOWNY_ODBIOR_WYMAGANY: ["SPOTKANIE_ZAPLANOWANE", "SPOR"],
  PROBLEM_Z_PLATNOSCIA: [
    "OCZEKIWANIE_NA_OTWARCIE_TERMINALU",
    "OCZEKUJE_NA_PLATNOSC",
    "OCZEKUJE_NA_WERYFIKACJE",
    "SPOR",
  ],
  WPLATA_POTWIERDZONA_OBUSTRONNIE: [
    "PRZEDMIOT_PRZEKAZANY",
    "ODMOWA_PRZEKAZANIA",
  ],
  WPLATA_NIEUDANA: ["OCZEKIWANIE_NA_OTWARCIE_TERMINALU", "SPOR"],
  WPLATA_WYMAGA_WYJASNIENIA: ["SPOR", "OCZEKIWANIE_NA_OTWARCIE_TERMINALU"],
  PRZEDMIOT_PRZEKAZANY: ["ZAKONCZONA_POMYSLNIE"],
  ZAKONCZONA_POMYSLNIE: [],
  ZWYCIEZCA_NIE_POTWIERDZIL: [],
  NIEOBECNOSC_KUPUJACEGO: ["SPOTKANIE_ZAPLANOWANE", "SPOR"],
  NIEOBECNOSC_WYSTAWIAJACEGO: ["SPOTKANIE_ZAPLANOWANE", "SPOR"],
  PRZEDMIOT_NIEZGODNY_Z_OPISEM: ["SPOR"],
  WPLATA_NIEPOTWIERDZONA: ["OCZEKIWANIE_NA_OTWARCIE_TERMINALU", "SPOR"],
  ODMOWA_PRZEKAZANIA: ["SPOR"],
  SPOR: ["ZAKONCZONA_POMYSLNIE", "ANULOWANA"],
  ANULOWANA: [],
};


export function normalizeTransactionStatus(status: string): TransactionStatus {
  if (status === "OCZEKIWANIE_NA_WPLATE") return "OCZEKUJE_NA_PLATNOSC";
  if (status === "WPLATA_ZWERYFIKOWANA" || status === "WPLATA_POTWIERDZONA") {
    return "WPLATA_POTWIERDZONA_OBUSTRONNIE";
  }
  if (status in TRANSACTION_TRANSITIONS) return status as TransactionStatus;
  throw new Error(`Nieznany status transakcji: ${status}.`);
}

export function canTransitionTransaction(
  from: string,
  to: TransactionStatus,
): boolean {
  return TRANSACTION_TRANSITIONS[normalizeTransactionStatus(from)]?.includes(to) ?? false;
}

/** Przedmiot można wydać dopiero po niezależnym potwierdzeniu wpłaty przez obie strony. */
export function canHandOverItem(status: string): boolean {
  return normalizeTransactionStatus(status) === "WPLATA_POTWIERDZONA_OBUSTRONNIE";
}

export function assertNotSelfBid(listingOwnerId: string, bidderId: string): void {
  if (listingOwnerId === bidderId) throw new Error("SELF_BID_FORBIDDEN");
}
