import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/db";
import { listings,userProfiles,users,ratings } from "@/db/schema";
import { desc,eq } from "drizzle-orm";
import { Badge,EmptyState } from "@/components/ui";
import { CheckIcon, MapPinIcon, StarIcon } from "@/components/icons";
import { formatMoney } from "@/lib/auction-logic";
export const dynamic="force-dynamic";
export default async function Page({params}:{params:Promise<{nickname:string}>}){const {nickname}=await params;const [u]=await db.select().from(users).where(eq(users.nickname,nickname)).limit(1);if(!u)notFound();const [[p],items,reviews]=await Promise.all([db.select().from(userProfiles).where(eq(userProfiles.userId,u.id)).limit(1),db.select().from(listings).where(eq(listings.userId,u.id)).orderBy(desc(listings.createdAt)),db.select().from(ratings).where(eq(ratings.ratedId,u.id)).orderBy(desc(ratings.createdAt)).limit(20)]);const publicItems=items.filter((i)=>["AKTYWNA","ZAKONCZONA"].includes(i.status));const initials=u.nickname.slice(0,2).toUpperCase();return <main className="page-shell max-w-5xl py-12">
  <section className="grid gap-7 border-b border-slate-200 pb-9 sm:grid-cols-[auto_1fr]"><span className="flex h-20 w-20 items-center justify-center rounded-full bg-brand-100 text-xl font-bold text-brand-800">{initials}</span><div><div className="flex flex-wrap items-center gap-3"><h1 className="text-3xl font-bold tracking-[-.03em] text-ink">{u.nickname}</h1>{u.emailVerifiedAt&&<Badge tone="success"><CheckIcon size={12}/> E-mail potwierdzony</Badge>}{u.phoneVerifiedAt&&<Badge tone="success"><CheckIcon size={12}/> Telefon potwierdzony</Badge>}{u.identityVerifiedAt&&<Badge tone="brand"><CheckIcon size={12}/> Tożsamość potwierdzona</Badge>}{u.trustedSellerAt&&<Badge tone="accent">Zaufany wystawiający</Badge>}{u.localPartnerAt&&<Badge tone="accent">Lokalny partner</Badge>}{u.volunteerAt&&<Badge tone="accent">Wolontariusz</Badge>}</div><p className="mt-2 inline-flex items-center gap-1.5 text-sm text-slate-500"><MapPinIcon size={15}/>{u.city} · konto od {u.createdAt.toLocaleDateString("pl-PL")}</p><div className="mt-5 grid grid-cols-2 gap-5 sm:grid-cols-4"><ProfileStat value={Number(p?.ratingAvg??0).toFixed(1)} label="średnia ocen"/><ProfileStat value={p?.completedTransactions??0} label="transakcje"/><ProfileStat value={p?.ratingCount??0} label="oceny"/><ProfileStat value={formatMoney(p?.totalForCampaign??0)} label="wartość pomocy"/></div>{(p?.badges??[]).length>0&&<div className="mt-5 flex flex-wrap gap-2">{(p?.badges??[]).map((b)=><Badge key={b} tone="accent">{b}</Badge>)}</div>}</div></section>
  <section className="mt-10"><h2 className="text-xl font-bold text-ink">Aukcje użytkownika</h2>{publicItems.length?<div className="mt-4 grid gap-4 sm:grid-cols-2">{publicItems.map((i)=><Link key={i.id} href={`/aukcje/${i.id}`} className="rounded-xl border border-slate-200 bg-white p-5 hover:border-brand-400"><p className="font-semibold text-ink">{i.title}</p><p className="mt-2 text-xs text-slate-500">{i.status==="AKTYWNA"?"Aktywna aukcja":"Zakończona"}</p></Link>)}</div>:<div className="mt-4"><EmptyState title="Brak publicznych aukcji" description="Ten użytkownik nie ma obecnie publicznych ofert."/></div>}</section>
  <section className="mt-10"><h2 className="text-xl font-bold text-ink">Oceny po transakcjach</h2>{reviews.length?<div className="mt-4 divide-y divide-slate-200 border-y border-slate-200">{reviews.map((r)=><article key={r.id} className="py-5"><div className="flex items-center gap-1 text-amber-500">{Array.from({length:5},(_,idx)=><StarIcon key={idx} size={15} className={idx<r.stars?"fill-amber-400":"text-slate-300"}/>)}</div>{r.comment&&<p className="mt-3 text-sm leading-6 text-slate-600">{r.comment}</p>}</article>)}</div>:<p className="mt-4 text-sm text-slate-500">Brak ocen.</p>}</section>
</main>}
function ProfileStat({value,label}:{value:string|number;label:string}){return <div><p className="text-xl font-bold text-brand-800">{value}</p><p className="mt-1 text-xs text-slate-500">{label}</p></div>}
